[package]
name = "ptcov"
version = "0.1.3"
authors = ["Marco Cavenati <cavenatimarco+ptcov@gmail.com>"]
edition = "2024"
rust-version = "1.92.0"
license = "MIT OR Apache-2.0"
description = "Decoder to compute code coverage from Intel® Processor Trace traces"
documentation = "https://docs.rs/ptcov"
readme = "README.md"
repository = "https://github.com/Marcondiro/ptcov"
keywords = ["decoder", "intel", "pt"]
categories = ["development-tools::testing"]

[features]
default = [
  "cyc",
  "indirect_edges",
  "more_checks",
  "ptw",
  "retc",
  "stronger_hash",
]
# Support for IA32_RTIT_CTL.CYCEn dependent packets
cyc = []
# NOT YET IMPLEMENTED - Support PEBS output to PT trace.
# When IA32_PERF_CAPABILITIES.PEBS_OUTPUT_PT_AVAIL[16] and IA32_PEBS_ENABLE.OUTPUT [62:61] == 0b01
pebs = []
# Support for IA32_RTIT_CTL.PTWEn dependent packets
ptw = []
# Support Indirect Transfer Compression for Returns (RET). Required if IA32_RTIT_CTL.DisRETC == 0
retc = []

# Perform more consistency checks even if not strictly necessary for trace decoding.
# Without this feature, decoding might not detect inconsistencies in traces and give less precise errors.
more_checks = []
# Use a stronger hasher when filling the coverage map
stronger_hash = []
# Track edges originating from indirect jumps/calls/ret into the coverage map
indirect_edges = []

log = ["log_packets", "log_instructions"]
log_packets = []
log_instructions = []

[package.metadata.cargo-all-features]
denylist = ["pebs"]

[lints.rust]
missing_docs = "warn"

[dependencies]
hashbrown = "0.17.1"
iced-x86 = { version = "1.21.0", default-features = false, features = [
  "std",
  "decoder",
  "instr_info",
] }
log = { version = "0.4.32" }
num-traits = "0.2.19"

[dev-dependencies]
env_logger = "0.11.10"

[lints.clippy]
alloc_instead_of_core = "deny"
std_instead_of_alloc = "deny"
std_instead_of_core = "deny"
